//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// ModelViewer.rc で使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_ModelViewerTYPE             130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_JSONVIEW                132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDS_JSON_VIEW                   159
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_DIALOG_OPEN_AVRO            307
#define IDR_AVRO_VIEW_POPUP             308
#define IDD_DIALOG_PROPERTY             309
#define IDD_DIALOG_AVRO_PROPERTY        310
#define IDD_DIALOG_LOOKAT               315
#define IDD_DIALOG_SHAPE_FACE_CONE      318
#define IDD_DIALOG_ENTITY_PROPERTY      319
#define IDD_DIALOG_SHARE_FACE_PLANE     320
#define IDD_DIALOG_SHAPE_FACE_PLANE     320
#define IDD_DIALOG_API_SUBTRACT         322
#define IDD_DIALOG_SHAPE_EDGE_STRAIGHT  324
#define IDD_DIALOG_SHAPE_POINT          326
#define IDR_POPUP_JSON                  330
#define IDC_EDIT_AVRO                   1000
#define IDC_EDIT_SCHEMA                 1001
#define IDC_BUTTON_SCHEMA               1002
#define IDC_BUTTON_AVRO                 1003
#define IDC_RADIO_IMPORT_MODE           1004
#define IDC_RADIO_FR_SHM_EXEC           1005
#define IDC_CHECK_EXPORT_EDGE           1007
#define IDC_EDIT_TARGET_PICK            1008
#define IDC_EDIT_PROPERTY               1009
#define IDC_EDIT_CENTER_X               1010
#define IDC_EDIT_ORIGIN_X               1011
#define IDC_EDIT_START_X                1012
#define IDC_EDIT_POINT_Y                1013
#define IDC_EDIT_CENTER_Y               1014
#define IDC_EDIT_FACE_PICK              1015
#define IDC_EDIT_CENTER_Z               1016
#define IDC_EDIT_SHAPE_FACE_CONE_NORMAL_X 1018
#define IDC_EDIT_LOOKAT_X               1019
#define IDC_EDIT_ORIGIN_Y               1020
#define IDC_EDIT_END_X                  1021
#define IDC_EDIT_SHAPE_FACE_CONE_NORMAL_Z 1022
#define IDC_EDIT_LOOKAT_Y               1023
#define IDC_EDIT_ORIGIN_Z               1025
#define IDC_EDIT_CENTER_Z2              1026
#define IDC_EDIT_LOOKAT_Z               1027
#define IDC_EDIT_NORMAL_X               1029
#define IDC_EDIT_SHAPE_FACE_CONE_RADIUS 1030
#define IDC_EDIT_NORMAL_Y               1032
#define IDC_EDIT_SHAPE_FACE_CONE_SINT   1033
#define IDC_EDIT_WIDTH                  1034
#define IDC_EDIT_SHAPE_FACE_CONE_NORMAL_Y 1035
#define IDC_EDIT_START_Y                1037
#define IDC_EDIT_SHAPE_FACE_CONE_COST   1038
#define IDC_EDIT_NORMAL_Z               1039
#define IDC_EDIT_START_Z                1040
#define IDC_SHAPE_FACE_CONE_EDIT_NORMAL_Z 1041
#define IDC_EDIT_TARGET_PICK3           1042
#define IDC_EDIT_HEIGHT                 1043
#define IDC_EDIT_END_Z                  1044
#define IDC_EDIT_POINT_X                1045
#define IDC_EDIT_SHAPE_FACE_CONE_MAJOR_X 1046
#define IDC_EDIT_END_Y                  1048
#define IDC_EDIT_POINT_Z                1049
#define IDC_EDIT_SHAPE_FACE_CONE_START_ANG 1050
#define IDC_EDIT_SHAPE_FACE_CONE_END_ANG 1052
#define IDC_EDIT_TARGET_PICK0           1053
#define IDC_EDIT_SHAPE_FACE_CONE_HEIGHT 1054
#define IDC_TARGET_PICK_BUTTON          1055
#define IDC_EDIT_SHAPE_FACE_CONE_MAJOR_Y 1056
#define IDC_FACE_PICK_BUTTON            1057
#define IDC_EDIT_SHAPE_FACE_CONE_CENTER_Z 1058
#define IDC_EDIT_SHAPE_FACE_CONE_CENTER_X 1060
#define IDC_EDIT_SHAPE_FACE_CONE_CENTER_Y 1061
#define IDC_EDIT_SHAPE_FACE_CONE_MAJOR_Z 1062
#define ID_VIEW_ROTATION                32771
#define ID_VIEW_PAN                     32772
#define ID_VIEW_ZOOM                    32773
#define ID_VIEW_RENDERPOINT             32774
#define ID_VIEW_RENDERLINE              32775
#define ID_VIEW_RENDERFACE              32776
#define ID_VIEW_PICKPOINT               32777
#define ID_VIEW_PICKLINE                32778
#define ID_VIEW_PICKFACE                32779
#define ID_FILE_OPEN_ADD                32780
#define ID_FILE_OPEN_AVRO               32781
#define ID_AVRO_ARROW                   32782
#define ID_POPUP_PROPERTY               32798
#define ID_LOOKAT_CENTER                32799
#define ID_SHAPE_WIRE                   32800
#define ID_EDGE_STRAIGHT                32805
#define ID_EDGE_ELLIPSE                 32806
#define ID_SHAPE_FACE_CONE              32807
#define ID_SHAPE_FACE_PLANE             32808
#define ID_API_SUBTRACT                 32809
#define ID_PICK                         32811
#define ID_FILE_OPEN_JSON               32813
#define ID_SHAPE_POINT                  32814
#define ID_SHAPE_EDGE_STRAIGHT          32815
#define ID_SHAPE_EDGE_ELLIPSE           32816
#define ID_SOLID_BLOCK                  32817
#define ID_SOLID_CYLINDER               32818
#define ID_SOLID_SPHERE                 32819
#define ID_SOLID_TORUS                  32820
#define ID_SHAPE_SOLID_BLOCK            32821
#define ID_SHAPE_SOLID_CYLINDER         32822
#define ID_SHAPE_SOLID_SPHERE           32823
#define ID_SHAPE_SOLID_TORUS            32824
#define ID_FACE_SPHERE                  32825
#define ID_FACE_SPLINE                  32826
#define ID_FACE_TORUS                   32827
#define ID_SHAPE_FACE_SPHERE            32828
#define ID_SHAPE_FACE_SPLINE            32829
#define ID_SHAPE_FACE_TORUS             32830
#define ID_POPUP_PICK                   32831
#define ID_POPUP_JSON_PICK              32832
#define ID_POPUP_JSON_CLEAR             32833
#define ID_API_UNITE                    32834

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        331
#define _APS_NEXT_COMMAND_VALUE         32835
#define _APS_NEXT_CONTROL_VALUE         1026
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
